### ISSUE TITLE
Race condition in tracking max sequence nr on delete

### ISSUE THREAD

**Issue by scullxbones** [scullxbones/akka-persistence-mongo#151]
```
DeleteMessagesFailure
com.mongodb.DuplicateKeyException: Write failed with error code 11000 and error message 'E11000 duplicate key error collection: akka-persistence.akka_persistence_metadata index: akka_persistence_metadata_pid dup key: { : "<pid>" }'
```

**Comment by scullxbones** [comment]
Fixed in `1.4.2` and `2.0.1`

**Comment by gbrd** [comment]
I rerun the same test on the same database and I still have an issue in 2.0.1.
Did not had enough time for now to analyse sorry.

```
09:10:15.445UTC ERROR [MySystem-akka.actor.default-dispatcher-14] akka.tcp://MySystem@127.0.0.1:2551/system/sharding/AAA/-1/foo1474034644326/bar - DeleteMessagesFailure
com.mongodb.DuplicateKeyException: Write failed with error code 11000 and error message 'E11000 duplicate key error collection: akka-persistence.akka_persistence_metadata index: akka_persistence_metadata_pid dup key: { : "/AAA/foo1474034644326" }'
	at com.mongodb.operation.BaseWriteOperation.convertBulkWriteException(BaseWriteOperation.java:236)
	at com.mongodb.operation.BaseWriteOperation.access$300(BaseWriteOperation.java:60)
	at com.mongodb.operation.BaseWriteOperation$1.call(BaseWriteOperation.java:146)
	at com.mongodb.operation.BaseWriteOperation$1.call(BaseWriteOperation.java:133)
	at com.mongodb.operation.OperationHelper.withConnectionSource(OperationHelper.java:230)
	at com.mongodb.operation.OperationHelper.withConnection(OperationHelper.java:221)
	at com.mongodb.operation.BaseWriteOperation.execute(BaseWriteOperation.java:133)
	at com.mongodb.operation.BaseWriteOperation.execute(BaseWriteOperation.java:60)
	at com.mongodb.Mongo.execute(Mongo.java:781)
	at com.mongodb.Mongo$2.execute(Mongo.java:764)
	at com.mongodb.DBCollection.executeWriteOperation(DBCollection.java:333)
	at com.mongodb.DBCollection.updateImpl(DBCollection.java:495)
	at com.mongodb.DBCollection.update(DBCollection.java:455)
	at com.mongodb.casbah.MongoCollectionBase$class.update(MongoCollection.scala:869)
	at com.mongodb.casbah.MongoCollection.update(MongoCollection.scala:1106)
	at akka.contrib.persistence.mongodb.CasbahPersistenceJournaller.akka$contrib$persistence$mongodb$CasbahPersistenceJournaller$$setMaxSequenceMetadata(CasbahPersistenceJournaller.scala:86)
	at akka.contrib.persistence.mongodb.CasbahPersistenceJournaller$$anonfun$deleteFrom$1$$anonfun$apply$mcV$sp$1.apply(CasbahPersistenceJournaller.scala:114)
	at akka.contrib.persistence.mongodb.CasbahPersistenceJournaller$$anonfun$deleteFrom$1$$anonfun$apply$mcV$sp$1.apply(CasbahPersistenceJournaller.scala:114)
	at scala.Option.foreach(Option.scala:257)
	at akka.contrib.persistence.mongodb.CasbahPersistenceJournaller$$anonfun$deleteFrom$1.apply$mcV$sp(CasbahPersistenceJournaller.scala:114)
	at akka.contrib.persistence.mongodb.CasbahPersistenceJournaller$$anonfun$deleteFrom$1.apply(CasbahPersistenceJournaller.scala:103)
	at akka.contrib.persistence.mongodb.CasbahPersistenceJournaller$$anonfun$deleteFrom$1.apply(CasbahPersistenceJournaller.scala:103)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:38)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:43)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
  
  ```

**Comment by scullxbones** [comment]
Hmm.  Ok.  Well sounds like it's not fixed then.

**Comment by scullxbones** [comment]
Hmm, not how I understand atomic operations, but apparently the error is by design:

- [SERVER-22607](https://jira.mongodb.org/browse/SERVER-22607)
- [From the docs](https://docs.mongodb.com/v2.4/reference/method/db.collection.update/#upsert-behavior)
- [stack overflow post](https://stackoverflow.com/questions/29305405/mongodb-impossible-e11000-duplicate-key-error-dup-key-when-upserting) 

I'll have to handle as a try/catch.

**Comment by scullxbones** [comment]
@gbrd - I've published a snapshot version `2.0.2-SNAPSHOT` that I think should solve the problem based on the above.  Is it possible that you could rerun your test and validate that the fix works?

**Comment by gbrd** [comment]
Thanks.  I should be able to test on next tuesday.

**Comment by gbrd** [comment]
I did not reproduce the same error.
I had other error messages but it has probably no connection with this issue (and may even have been present is my previous tests). I copy logs here just in case.. 



in my persistent actor : 
```
case SaveSnapshotFailure(metadata, reason) => log.warning(s"snap err $reason")
```
it gives:
```
 snap err com.mongodb.WriteConcernException: Write failed with error code 96 and error message 'Exec error: PlanExecutor killed'
```


and: 
```
case DeleteMessagesFailure(t, _) =>  log.error(t, "DeleteMessagesFailure")
```
gives:

```

DeleteMessagesFailure
com.mongodb.MongoCommandException: Command failed with error 16028: 'exception: collection or index disappeared when cursor yielded' on server 127.0.0.1:27017. The full response is { "errmsg" : "exception: collection or index disappeared when cursor yielded", "code" : 16028, "ok" : 0.0 }
	at com.mongodb.connection.ProtocolHelper.getCommandFailureException(ProtocolHelper.java:115)
	at com.mongodb.connection.CommandProtocol.execute(CommandProtocol.java:114)
	at com.mongodb.connection.DefaultServer$DefaultServerProtocolExecutor.execute(DefaultServer.java:159)
	at com.mongodb.connection.DefaultServerConnection.executeProtocol(DefaultServerConnection.java:286)
	at com.mongodb.connection.DefaultServerConnection.command(DefaultServerConnection.java:173)
	at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:215)
	at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:206)
	at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:112)
	at com.mongodb.operation.AggregateOperation$1.call(AggregateOperation.java:227)
	at com.mongodb.operation.AggregateOperation$1.call(AggregateOperation.java:223)
	at com.mongodb.operation.OperationHelper.withConnectionSource(OperationHelper.java:239)
	at com.mongodb.operation.OperationHelper.withConnection(OperationHelper.java:212)
	at com.mongodb.operation.AggregateOperation.execute(AggregateOperation.java:223)
	at com.mongodb.operation.AggregateOperation.execute(AggregateOperation.java:65)
	at com.mongodb.Mongo.execute(Mongo.java:772)
	at com.mongodb.Mongo$2.execute(Mongo.java:759)
	at com.mongodb.DBCollection.aggregate(DBCollection.java:1377)
	at com.mongodb.DBCollection.aggregate(DBCollection.java:1308)
	at com.mongodb.DBCollection.aggregate(DBCollection.java:1294)
	at com.mongodb.casbah.MongoCollectionBase$class.aggregate(MongoCollection.scala:673)
	at com.mongodb.casbah.MongoCollection.aggregate(MongoCollection.scala:1106)
	at akka.contrib.persistence.mongodb.CasbahPersistenceJournaller.akka$contrib$persistence$mongodb$CasbahPersistenceJournaller$$findMaxSequence(CasbahPersistenceJournaller.scala:82)
	at akka.contrib.persistence.mongodb.CasbahPersistenceJournaller$$anonfun$deleteFrom$1.apply$mcV$sp(CasbahPersistenceJournaller.scala:118)
	at akka.contrib.persistence.mongodb.CasbahPersistenceJournaller$$anonfun$deleteFrom$1.apply(CasbahPersistenceJournaller.scala:109)
	at akka.contrib.persistence.mongodb.CasbahPersistenceJournaller$$anonfun$deleteFrom$1.apply(CasbahPersistenceJournaller.scala:109)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:38)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:43)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by scullxbones** [comment]
Ok, i'm marking this issue fixed in `2.0.2` and `1.4.2`.  Thanks for the report and SNAPSHOT test!

**Comment by scullxbones** [comment]
It looks like I never released 1.4.3, addressing this now.
